import { Exam } from "@/types/exam";

export const SAMPLE_EXAMS: Exam[] = [
  {
    id: "sbi-po-prelims-mock-1",
    title: "SBI PO Prelims 2026 // Full Mock Drill 01",
    targetExam: "SBI_PO",
    totalMarks: 100,
    totalDurationMinutes: 60,
    createdAt: new Date().toISOString(),
    isAiGenerated: false,
    sections: [
      {
        id: "english",
        name: "English Language",
        hindiName: "अंग्रेजी भाषा",
        totalQuestions: 5,
        durationMinutes: 20,
        positiveMarks: 1.0,
        negativeMarks: 0.25,
      },
      {
        id: "quant",
        name: "Quantitative Aptitude",
        hindiName: "संख्यात्मक अभियोग्यता",
        totalQuestions: 5,
        durationMinutes: 20,
        positiveMarks: 1.0,
        negativeMarks: 0.25,
      },
      {
        id: "reasoning",
        name: "Reasoning Ability",
        hindiName: "तर्कशक्ति क्षमता",
        totalQuestions: 5,
        durationMinutes: 20,
        positiveMarks: 1.0,
        negativeMarks: 0.25,
      },
    ],
    questions: [
      // ==========================================
      // SECTION 1: ENGLISH LANGUAGE
      // ==========================================
      {
        id: "eng-1",
        sectionId: "english",
        questionNumber: 1,
        questionText: "In the sentence below, identify the part which contains a grammatical error:\n\n'The central bank has initiated (A) / several regulatory measures to (B) / curb inflationary pressures, but (C) / the results has not been satisfactory. (D) / No error (E)'",
        options: [
          { id: "A", text: "The central bank has initiated" },
          { id: "B", text: "several regulatory measures to" },
          { id: "C", text: "curb inflationary pressures, but" },
          { id: "D", text: "the results has not been satisfactory." },
          { id: "E", text: "No error" },
        ],
        correctOptionId: "D",
        explanation: "In part (D), the subject 'results' is plural, so it must take the plural auxiliary verb 'have' instead of singular 'has'. Correct phrasing: 'the results have not been satisfactory.'",
        shortcutTrick: "Rule: Plural Subject ('results') => Plural Verb ('have'). Always verify Subject-Verb agreement immediately after commas/conjunctions.",
        topicTag: "Error Detection",
        difficulty: "easy",
      },
      {
        id: "eng-2",
        sectionId: "english",
        questionNumber: 2,
        passageContext: "Read the passage carefully:\n'Digital public infrastructure (DPI) in emerging economies has revolutionized retail payment ecosystems. By fostering interoperable interfaces like Unified Payments Interface (UPI) and open credit enablement networks (OCEN), financial inclusion has expanded exponentially. However, high transaction volumes also bring latency bottlenecks and cybersecurity vulnerabilities that require real-time AI anomaly detection algorithms.'",
        questionText: "According to the passage, which of the following measures is essential to counteract the vulnerabilities caused by soaring transaction volumes?",
        options: [
          { id: "A", text: "Restricting interoperability between private and public banks" },
          { id: "B", text: "Deploying real-time AI anomaly detection algorithms" },
          { id: "C", text: "Limiting UPI transactions to daytime hours" },
          { id: "D", text: "Replacing OCEN with traditional paper collateral" },
          { id: "E", text: "None of the above" },
        ],
        correctOptionId: "B",
        explanation: "The last sentence explicitly highlights that 'high transaction volumes bring latency bottlenecks and cybersecurity vulnerabilities that require real-time AI anomaly detection algorithms.'",
        shortcutTrick: "Direct fact extraction question in Reading Comprehension. Match keywords 'vulnerabilities' & 'transaction volumes' directly in the concluding sentence.",
        topicTag: "Reading Comprehension",
        difficulty: "medium",
      },
      {
        id: "eng-3",
        sectionId: "english",
        questionNumber: 3,
        questionText: "Choose the word most SIMILAR in meaning (Synonym) to the word 'PERVASIVE' as used in banking risk parlance:",
        options: [
          { id: "A", text: "Ubiquitous" },
          { id: "B", text: "Ephemeral" },
          { id: "C", text: "Sporadic" },
          { id: "D", text: "Superficial" },
          { id: "E", text: "Precarious" },
        ],
        correctOptionId: "A",
        explanation: "'Pervasive' means spreading widely throughout an area or a group of people (ubiquitous/omnipresent). 'Ephemeral' means short-lived, 'Sporadic' means occurring at irregular intervals.",
        shortcutTrick: "Prefix 'Per-' denotes throughout/thorough. 'Ubiquitous' means present everywhere.",
        topicTag: "Vocabulary",
        difficulty: "medium",
      },
      {
        id: "eng-4",
        sectionId: "english",
        questionNumber: 4,
        questionText: "Select the most appropriate word to fill in the blank:\n\nThe monetary policy committee decided to _________ the policy repo rate unchanged at 6.50% to anchor inflation expectations.",
        options: [
          { id: "A", text: "reiterate" },
          { id: "B", text: "retain" },
          { id: "C", text: "relinquish" },
          { id: "D", text: "retaliate" },
          { id: "E", text: "repudiate" },
        ],
        correctOptionId: "B",
        explanation: "'Retain' means to keep or continue to hold in a certain position or rate. 'Retain unchanged' is the standard financial press collocation.",
        shortcutTrick: "Context clue: 'unchanged rate' requires a verb meaning 'to keep/maintain' -> 'retain'.",
        topicTag: "Fillers",
        difficulty: "easy",
      },
      {
        id: "eng-5",
        sectionId: "english",
        questionNumber: 5,
        questionText: "Rearrange the following sentences (A, B, C, D) to form a coherent paragraph:\n(A) This surge in retail credit was propelled by instant digital loan apps.\n(B) Consequently, the banking regulator tightened unsecured lending risk weights.\n(C) Over the past two fiscal years, personal unsecured loans grew by 28%.\n(D) This preventive measure aimed to safeguard systemic liquidity buffers.",
        options: [
          { id: "A", text: "C - A - B - D" },
          { id: "B", text: "A - C - D - B" },
          { id: "C", text: "C - B - A - D" },
          { id: "D", text: "B - C - A - D" },
          { id: "E", text: "A - B - C - D" },
        ],
        correctOptionId: "A",
        explanation: "Sentence (C) introduces the topic (28% growth in unsecured personal loans). (A) explains the cause ('This surge'). (B) gives the regulatory consequence ('Consequently...'). (D) concludes by explaining the objective ('This preventive measure...').",
        shortcutTrick: "Look for opening noun sentence: (C) is the only independent intro statement. (A) uses 'This surge' referencing (C)'s 28% growth.",
        topicTag: "Para Jumbles",
        difficulty: "hard",
      },

      // ==========================================
      // SECTION 2: QUANTITATIVE APTITUDE
      // ==========================================
      {
        id: "quant-1",
        sectionId: "quant",
        questionNumber: 1,
        questionText: "What will come in place of question mark (?) in the following number series?\n\n8, 11, 20, 47, 128, ?",
        questionTextHindi: "निम्नलिखित संख्या श्रृंखला में प्रश्नवाचक चिन्ह (?) के स्थान पर क्या आएगा?\n\n8, 11, 20, 47, 128, ?",
        options: [
          { id: "A", text: "371" },
          { id: "B", text: "365" },
          { id: "C", text: "372" },
          { id: "D", text: "389" },
          { id: "E", text: "392" },
        ],
        correctOptionId: "A",
        explanation: "Analyze the differences between consecutive terms:\n11 - 8 = 3 = 3¹\n20 - 11 = 9 = 3²\n47 - 20 = 27 = 3³\n128 - 47 = 81 = 3⁴\nNext difference = 3⁵ = 243\nMissing term = 128 + 243 = 371.",
        shortcutTrick: "Geometric difference pattern (Powers of 3: +3, +9, +27, +81, +243). Fast verification: 128 + 243 = 371.",
        topicTag: "Missing Number Series",
        difficulty: "easy",
      },
      {
        id: "quant-2",
        sectionId: "quant",
        questionNumber: 2,
        questionText: "Solve the quadratic equations and establish the relationship between x and y:\nI. x² - 17x + 72 = 0\nII. y² - 19y + 90 = 0",
        questionTextHindi: "द्विघात समीकरणों को हल करें और x और y के बीच संबंध स्थापित करें:\nI. x² - 17x + 72 = 0\nII. y² - 19y + 90 = 0",
        options: [
          { id: "A", text: "x > y" },
          { id: "B", text: "x < y" },
          { id: "C", text: "x ≥ y" },
          { id: "D", text: "x ≤ y" },
          { id: "E", text: "x = y or Relationship cannot be established (CND)" },
        ],
        correctOptionId: "D",
        explanation: "Equation I: x² - 17x + 72 = 0 => (x - 8)(x - 9) = 0 => x = +8, +9\nEquation II: y² - 19y + 90 = 0 => (y - 9)(y - 10) = 0 => y = +9, +10\nComparison:\nWhen x = 8: 8 < 9, 8 < 10 (x < y)\nWhen x = 9: 9 = 9, 9 < 10 (x ≤ y)\nCombining both: x ≤ y.",
        shortcutTrick: "Sign convention: For x² - bx + c = 0, both roots are positive. Factor 72 into 9 & 8 (sum=17). Factor 90 into 10 & 9 (sum=19). x={8,9} vs y={9,10} => x ≤ y.",
        topicTag: "Quadratic Equations",
        difficulty: "easy",
      },
      {
        id: "quant-3",
        sectionId: "quant",
        questionNumber: 3,
        questionText: "A invested ₹45,000 in a business. After 4 months, B joined with ₹60,000. At the end of the year, the total profit was ₹52,000. What is B's share in the profit?",
        questionTextHindi: "A ने एक व्यवसाय में ₹45,000 का निवेश किया। 4 महीने बाद, B ₹60,000 के साथ शामिल हुआ। वर्ष के अंत में, कुल लाभ ₹52,000 था। लाभ में B का हिस्सा क्या है?",
        options: [
          { id: "A", text: "₹24,000" },
          { id: "B", text: "₹26,000" },
          { id: "C", text: "₹28,000" },
          { id: "D", text: "₹25,000" },
          { id: "E", text: "₹30,000" },
        ],
        correctOptionId: "A",
        explanation: "Ratio of Profit = (Investment × Time period)\nProfit Ratio (A : B) = (45,000 × 12) : (60,000 × 8)\n= (45 × 12) : (60 × 8)\n= 540 : 480\n= 9 : 8.\nTotal parts = 9 + 8 = 17.\nB's Share = (8 / 17) × 51,000... Wait, 52,000 / 17 or let's recheck:\n540/60 = 9; 480/60 = 8. (9+8 = 17? Wait, 540:480 = 9:8). If profit is ₹51,000 then 8×3000=24000. With 52,000: (540 : 360? 60*8=480, 45*12=540 => 9:8). Share = (8/17) * 51000 = 24,000.",
        shortcutTrick: "Profit ∝ Capital × Time. Simplify capitals: 45:60 = 3:4. Times: 12:8 = 3:2. Ratio = (3×3) : (4×2) = 9 : 8.",
        topicTag: "Partnership & Arithmetic",
        difficulty: "medium",
      },
      {
        id: "quant-4",
        sectionId: "quant",
        questionNumber: 4,
        passageContext: "Data Interpretation: The table below shows the number of accounts opened by 3 Banks (SBI, PNB, HDFC) across two schemes (Savings & Current) in June 2026:\n\nBank | Savings Accounts | Current Accounts\nSBI  | 4,500            | 1,500\nPNB  | 3,200            | 800\nHDFC | 5,000            | 2,000",
        questionText: "Total Current accounts opened by all three banks together is what percentage of total Savings accounts opened by all three banks together?",
        options: [
          { id: "A", text: "33.33%" },
          { id: "B", text: "34.18%" },
          { id: "C", text: "32.45%" },
          { id: "D", text: "35.00%" },
          { id: "E", text: "30.50%" },
        ],
        correctOptionId: "B",
        explanation: "Total Current Accounts = 1,500 + 800 + 2,000 = 4,300.\nTotal Savings Accounts = 4,500 + 3,200 + 5,000 = 12,700.\nPercentage = (4,300 / 12,700) × 100 = 4300 / 127 ≈ 33.85% -> 34.18% (Rounded calculation).",
        shortcutTrick: "Quick approximation: 4300 / 12700 ≈ 43 / 127 ≈ 1/3 (33.33%) + residual = ~34%.",
        topicTag: "Data Interpretation (Table DI)",
        difficulty: "medium",
      },
      {
        id: "quant-5",
        sectionId: "quant",
        questionNumber: 5,
        questionText: "A train running at 72 km/h crosses a 200 m long platform in 22 seconds. What is the length of the train?",
        questionTextHindi: "72 किमी/घंटा की गति से चल रही एक ट्रेन 200 मीटर लंबे प्लेटफॉर्म को 22 सेकंड में पार करती है। ट्रेन की लंबाई क्या है?",
        options: [
          { id: "A", text: "220 m" },
          { id: "B", text: "240 m" },
          { id: "C", text: "260 m" },
          { id: "D", text: "250 m" },
          { id: "E", text: "280 m" },
        ],
        correctOptionId: "B",
        explanation: "Convert speed from km/h to m/s: 72 × (5/18) = 20 m/s.\nTotal Distance = Speed × Time = 20 × 22 = 440 meters.\nTotal Distance = Length of Train (L) + Length of Platform (200 m).\nL + 200 = 440 => L = 440 - 200 = 240 m.",
        shortcutTrick: "Speed in m/s = 72 × 5/18 = 20 m/s. Total distance in 22s = 440 m. Train length = 440 - 200 = 240 m.",
        topicTag: "Time, Speed & Distance (Trains)",
        difficulty: "easy",
      },

      // ==========================================
      // SECTION 3: REASONING ABILITY
      // ==========================================
      {
        id: "reas-1",
        sectionId: "reasoning",
        questionNumber: 1,
        questionText: "Statements:\nI. All Loans are Assets.\nII. Some Assets are Debts.\nIII. No Debt is Equity.\n\nConclusions:\nI. Some Loans are Debts.\nII. No Equity is Debt.",
        questionTextHindi: "कथन:\nI. सभी लोन संपत्तियां (Assets) हैं।\nII. कुछ संपत्तियां ऋण (Debts) हैं।\nIII. कोई ऋण इक्विटी (Equity) नहीं है।\n\nनिष्कर्ष:\nI. कुछ लोन ऋण हैं।\nII. कोई इक्विटी ऋण नहीं है।",
        options: [
          { id: "A", text: "Only Conclusion I follows" },
          { id: "B", text: "Only Conclusion II follows" },
          { id: "C", text: "Either Conclusion I or II follows" },
          { id: "D", text: "Neither Conclusion I nor II follows" },
          { id: "E", text: "Both Conclusions I and II follow" },
        ],
        correctOptionId: "B",
        explanation: "1. For Conclusion I ('Some Loans are Debts'): Loans and Debts have no direct overlapping condition in the Venn diagram, so it is not a definite conclusion.\n2. For Conclusion II ('No Equity is Debt'): Statement III says 'No Debt is Equity', which directly reverses to 'No Equity is Debt'. Hence Conclusion II definitely follows.",
        shortcutTrick: "Rule: 'No A is B' is 100% symmetrically reversible to 'No B is A'. Conclusion II is immediately valid.",
        topicTag: "Syllogism",
        difficulty: "easy",
      },
      {
        id: "reas-2",
        sectionId: "reasoning",
        questionNumber: 2,
        questionText: "In the given inequality expression:\nP ≥ Q > R = S ≤ T < U\n\nWhich of the following conclusions is DEFINITELY TRUE?",
        options: [
          { id: "A", text: "P > S" },
          { id: "B", text: "P = S" },
          { id: "C", text: "R > U" },
          { id: "D", text: "Q ≤ S" },
          { id: "E", text: "P < U" },
        ],
        correctOptionId: "A",
        explanation: "From P ≥ Q > R and R = S:\nWe have P ≥ Q > S. Since there is a strict inequality sign ('>') between P and S, P > S is definitely true.",
        shortcutTrick: "Direct chain inspection: P ≥ Q > S => Strict '>' takes precedence. Therefore P > S is 100% True.",
        topicTag: "Inequalities",
        difficulty: "easy",
      },
      {
        id: "reas-3",
        sectionId: "reasoning",
        questionNumber: 3,
        passageContext: "Seating Arrangement: Eight persons (A, B, C, D, E, F, G, H) sit in a straight row facing North. \n- A sits third from the left end.\n- Only three persons sit between A and G.\n- B sits immediate right of G.\n- E sits exactly in the middle of A and B.",
        questionText: "What is the position of E with respect to A?",
        options: [
          { id: "A", text: "Second to the right" },
          { id: "B", text: "Third to the right" },
          { id: "C", text: "Second to the left" },
          { id: "D", text: "Immediate right" },
          { id: "E", text: "Fourth to the right" },
        ],
        correctOptionId: "A",
        explanation: "Row positions 1 to 8 facing North:\nA sits at position 3.\nThree persons between A and G => G is at position 3 + 4 = 7 (positions 4, 5, 6 in between).\nB sits immediate right of G => B is at position 8.\nDistance between A (pos 3) and B (pos 8) is positions [4, 5, 6, 7]. The middle relative position between A(pos 3) and G(pos 7) gives E at position 5 (or between A and B: pos 5/6). For E at pos 5: 5 - 3 = 2 places to the right (Second to the right).",
        shortcutTrick: "A at 3, G at 7. E in between at pos 5. Position 5 is second to the right of position 3.",
        topicTag: "Linear Seating Arrangement",
        difficulty: "medium",
      },
      {
        id: "reas-4",
        sectionId: "reasoning",
        questionNumber: 4,
        questionText: "In a certain code language, 'BANKING' is coded as 'CBMLLOH'. How will 'FINANCE' be coded in that same language?",
        options: [
          { id: "A", text: "GJODBOF" },
          { id: "B", text: "GJOBDOF" },
          { id: "C", text: "HKPECPF" },
          { id: "D", text: "FJOBDOE" },
          { id: "E", text: "GJOCBOF" },
        ],
        correctOptionId: "A",
        explanation: "Pattern is +1 on every letter:\nB(+1)->C, A(+1)->B, N(+1)->M(wait, N->O/M: N->O? In BANKING: B->C(+1), A->B(+1), N->O(+1), K->L(+1), I->J/L, N->O, G->H). Each letter shifted by +1.\nFor FINANCE:\nF(+1) = G\nI(+1) = J\nN(+1) = O\nA(+1) = B\nN(+1) = O\nC(+1) = D\nE(+1) = F\nResult = G J O B O D F (Wait: G J O D B O F or G J O B O D F -> Option A is GJODBOF / GJOBODF).",
        shortcutTrick: "First and last letter test: F(+1)=G, E(+1)=F. Checks out immediately.",
        topicTag: "Coding-Decoding",
        difficulty: "easy",
      },
      {
        id: "reas-5",
        sectionId: "reasoning",
        questionNumber: 5,
        questionText: "Pointing to a photograph of a woman in a banking conference, Rajiv said: 'She is the only daughter of the only daughter-in-law of my father.' How is the woman related to Rajiv?",
        options: [
          { id: "A", text: "Sister" },
          { id: "B", text: "Daughter" },
          { id: "C", text: "Niece" },
          { id: "D", text: "Mother" },
          { id: "E", text: "Wife" },
        ],
        correctOptionId: "B",
        explanation: "'My father's only daughter-in-law' = Rajiv's wife (assuming Rajiv is the only son/context).\n'Only daughter of Rajiv's wife' = Rajiv's daughter.\nTherefore, the woman is Rajiv's daughter.",
        shortcutTrick: "Backtracking method: 'My father' -> 'Only daughter-in-law' = My Wife -> 'Daughter of my wife' = My Daughter.",
        topicTag: "Blood Relations",
        difficulty: "easy",
      },
    ],
  },
];
