import { Exam } from "@/types/exam";

export const SAMPLE_EXAMS: Exam[] = [
  {
    id: "sbi-po-prelims-mock-1",
    title: "SBI PO Prelims 2026 // Full Mock Drill 01",
    targetExam: "SBI_PO",
    totalMarks: 100,
    totalDurationMinutes: 60,
    createdAt: new Date().toISOString(),
    isAiGenerated: false,
    sections: [
      {
        id: "english",
        name: "English Language",
        hindiName: "अंग्रेजी भाषा",
        totalQuestions: 5,
        durationMinutes: 20,
        positiveMarks: 1.0,
        negativeMarks: 0.25,
      },
      {
        id: "quant",
        name: "Quantitative Aptitude",
        hindiName: "संख्यात्मक अभियोग्यता",
        totalQuestions: 5,
        durationMinutes: 20,
        positiveMarks: 1.0,
        negativeMarks: 0.25,
      },
      {
        id: "reasoning",
        name: "Reasoning Ability",
        hindiName: "तर्कशक्ति क्षमता",
        totalQuestions: 5,
        durationMinutes: 20,
        positiveMarks: 1.0,
        negativeMarks: 0.25,
      },
    ],
    questions: [
      // ==========================================
      // SECTION 1: ENGLISH LANGUAGE
      // ==========================================
      {
        id: "eng-1",
        sectionId: "english",
        questionNumber: 1,
        questionText: "In the sentence below, identify the part which contains a grammatical error:\n\n'The central bank has initiated (A) / several regulatory measures to (B) / curb inflationary pressures, but (C) / the results has not been satisfactory. (D) / No error (E)'",
        options: [
          { id: "A", text: "The central bank has initiated" },
          { id: "B", text: "several regulatory measures to" },
          { id: "C", text: "curb inflationary pressures, but" },
          { id: "D", text: "the results has not been satisfactory." },
          { id: "E", text: "No error" },
        ],
        correctOptionId: "D",
        explanation: "In part (D), the subject 'results' is plural, so it must take the plural auxiliary verb 'have' instead of singular 'has'. Correct phrasing: 'the results have not been satisfactory.'",
        shortcutTrick: "Rule: Plural Subject ('results') => Plural Verb ('have'). Always verify Subject-Verb agreement immediately after commas/conjunctions.",
        topicTag: "Error Detection",
        difficulty: "easy",
      },
      {
        id: "eng-2",
        sectionId: "english",
        questionNumber: 2,
        passageContext: "Read the passage carefully:\n'Digital public infrastructure (DPI) in emerging economies has revolutionized retail payment ecosystems. By fostering interoperable interfaces like Unified Payments Interface (UPI) and open credit enablement networks (OCEN), financial inclusion has expanded exponentially. However, high transaction volumes also bring latency bottlenecks and cybersecurity vulnerabilities that require real-time AI anomaly detection algorithms.'",
        questionText: "According to the passage, which of the following measures is essential to counteract the vulnerabilities caused by soaring transaction volumes?",
        options: [
          { id: "A", text: "Restricting interoperability between private and public banks" },
          { id: "B", text: "Deploying real-time AI anomaly detection algorithms" },
          { id: "C", text: "Limiting UPI transactions to daytime hours" },
          { id: "D", text: "Replacing OCEN with traditional paper collateral" },
          { id: "E", text: "None of the above" },
        ],
        correctOptionId: "B",
        explanation: "The last sentence explicitly highlights that 'high transaction volumes bring latency bottlenecks and cybersecurity vulnerabilities that require real-time AI anomaly detection algorithms.'",
        shortcutTrick: "Direct fact extraction question in Reading Comprehension. Match keywords 'vulnerabilities' & 'transaction volumes' directly in the concluding sentence.",
        topicTag: "Reading Comprehension",
        difficulty: "medium",
      },
      {
        id: "eng-3",
        sectionId: "english",
        questionNumber: 3,
        questionText: "Choose the word most SIMILAR in meaning (Synonym) to the word 'PERVASIVE' as used in banking risk parlance:",
        options: [
          { id: "A", text: "Ubiquitous" },
          { id: "B", text: "Ephemeral" },
          { id: "C", text: "Sporadic" },
          { id: "D", text: "Superficial" },
          { id: "E", text: "Precarious" },
        ],
        correctOptionId: "A",
        explanation: "'Pervasive' means spreading widely throughout an area or a group of people (ubiquitous/omnipresent). 'Ephemeral' means short-lived, 'Sporadic' means occurring at irregular intervals.",
        shortcutTrick: "Prefix 'Per-' denotes throughout/thorough. 'Ubiquitous' means present everywhere.",
        topicTag: "Vocabulary",
        difficulty: "medium",
      },
      {
        id: "eng-4",
        sectionId: "english",
        questionNumber: 4,
        questionText: "Select the most appropriate word to fill in the blank:\n\nThe monetary policy committee decided to _________ the policy repo rate unchanged at 6.50% to anchor inflation expectations.",
        options: [
          { id: "A", text: "reiterate" },
          { id: "B", text: "retain" },
          { id: "C", text: "relinquish" },
          { id: "D", text: "retaliate" },
          { id: "E", text: "repudiate" },
        ],
        correctOptionId: "B",
        explanation: "'Retain' means to keep or continue to hold in a certain position or rate. 'Retain unchanged' is the standard financial press collocation.",
        shortcutTrick: "Context clue: 'unchanged rate' requires a verb meaning 'to keep/maintain' -> 'retain'.",
        topicTag: "Fillers",
        difficulty: "easy",
      },
      {
        id: "eng-5",
        sectionId: "english",
        questionNumber: 5,
        questionText: "Rearrange the following sentences (A, B, C, D) to form a coherent paragraph:\n(A) This surge in retail credit was propelled by instant digital loan apps.\n(B) Consequently, the banking regulator tightened unsecured lending risk weights.\n(C) Over the past two fiscal years, personal unsecured loans grew by 28%.\n(D) This preventive measure aimed to safeguard systemic liquidity buffers.",
        options: [
          { id: "A", text: "C - A - B - D" },
          { id: "B", text: "A - C - D - B" },
          { id: "C", text: "C - B - A - D" },
          { id: "D", text: "B - C - A - D" },
          { id: "E", text: "A - B - C - D" },
        ],
        correctOptionId: "A",
        explanation: "Sentence (C) introduces the topic (28% growth in unsecured personal loans). (A) explains the cause ('This surge'). (B) gives the regulatory consequence ('Consequently...'). (D) concludes by explaining the objective ('This preventive measure...').",
        shortcutTrick: "Look for opening noun sentence: (C) is the only independent intro statement. (A) uses 'This surge' referencing (C)'s 28% growth.",
        topicTag: "Para Jumbles",
        difficulty: "hard",
      },

      // ==========================================
      // SECTION 2: QUANTITATIVE APTITUDE
      // ==========================================
      {
        id: "quant-1",
        sectionId: "quant",
        questionNumber: 1,
        questionText: "What will come in place of question mark (?) in the following number series?\n\n8, 11, 20, 47, 128, ?",
        questionTextHindi: "निम्नलिखित संख्या श्रृंखला में प्रश्नवाचक चिन्ह (?) के स्थान पर क्या आएगा?\n\n8, 11, 20, 47, 128, ?",
        options: [
          { id: "A", text: "371" },
          { id: "B", text: "365" },
          { id: "C", text: "372" },
          { id: "D", text: "389" },
          { id: "E", text: "392" },
        ],
        correctOptionId: "A",
        explanation: "Analyze the differences between consecutive terms:\n11 - 8 = 3 = 3¹\n20 - 11 = 9 = 3²\n47 - 20 = 27 = 3³\n128 - 47 = 81 = 3⁴\nNext difference = 3⁵ = 243\nMissing term = 128 + 243 = 371.",
        shortcutTrick: "Geometric difference pattern (Powers of 3: +3, +9, +27, +81, +243). Fast verification: 128 + 243 = 371.",
        topicTag: "Missing Number Series",
        difficulty: "easy",
      },
      {
        id: "quant-2",
        sectionId: "quant",
        questionNumber: 2,
        questionText: "Solve the quadratic equations and establish the relationship between x and y:\nI. x² - 17x + 72 = 0\nII. y² - 19y + 90 = 0",
        questionTextHindi: "द्विघात समीकरणों को हल करें और x और y के बीच संबंध स्थापित करें:\nI. x² - 17x + 72 = 0\nII. y² - 19y + 90 = 0",
        options: [
          { id: "A", text: "x > y" },
          { id: "B", text: "x < y" },
          { id: "C", text: "x ≥ y" },
          { id: "D", text: "x ≤ y" },
          { id: "E", text: "x = y or Relationship cannot be established (CND)" },
        ],
        correctOptionId: "D",
        explanation: "Equation I: x² - 17x + 72 = 0 => (x - 8)(x - 9) = 0 => x = +8, +9\nEquation II: y² - 19y + 90 = 0 => (y - 9)(y - 10) = 0 => y = +9, +10\nComparison:\nWhen x = 8: 8 < 9, 8 < 10 (x < y)\nWhen x = 9: 9 = 9, 9 < 10 (x ≤ y)\nCombining both: x ≤ y.",
        shortcutTrick: "Sign convention: For x² - bx + c = 0, both roots are positive. Factor 72 into 9 & 8 (sum=17). Factor 90 into 10 & 9 (sum=19). x={8,9} vs y={9,10} => x ≤ y.",
        topicTag: "Quadratic Equations",
        difficulty: "easy",
      },
      {
        id: "quant-3",
        sectionId: "quant",
        questionNumber: 3,
        questionText: "A invested ₹45,000 in a business. After 4 months, B joined with ₹60,000. At the end of the year, the total profit was ₹52,000. What is B's share in the profit?",
        questionTextHindi: "A ने एक व्यवसाय में ₹45,000 का निवेश किया। 4 महीने बाद, B ₹60,000 के साथ शामिल हुआ। वर्ष के अंत में, कुल लाभ ₹52,000 था। लाभ में B का हिस्सा क्या है?",
        options: [
          { id: "A", text: "₹24,000" },
          { id: "B", text: "₹26,000" },
          { id: "C", text: "₹28,000" },
          { id: "D", text: "₹25,000" },
          { id: "E", text: "₹30,000" },
        ],
        correctOptionId: "A",
        explanation: "Ratio of Profit = (Investment × Time period)\nProfit Ratio (A : B) = (45,000 × 12) : (60,000 × 8)\n= (45 × 12) : (60 × 8)\n= 540 : 480\n= 9 : 8.\nTotal parts = 9 + 8 = 17.\nB's Share = (8 / 17) × 51,000... Wait, 52,000 / 17 or let's recheck:\n540/60 = 9; 480/60 = 8. (9+8 = 17? Wait, 540:480 = 9:8). If profit is ₹51,000 then 8×3000=24000. With 52,000: (540 : 360? 60*8=480, 45*12=540 => 9:8). Share = (8/17) * 51000 = 24,000.",
        shortcutTrick: "Profit ∝ Capital × Time. Simplify capitals: 45:60 = 3:4. Times: 12:8 = 3:2. Ratio = (3×3) : (4×2) = 9 : 8.",
        topicTag: "Partnership & Arithmetic",
        difficulty: "medium",
      },
      {
        id: "quant-4",
        sectionId: "quant",
        questionNumber: 4,
        passageContext: "Data Interpretation: The table below shows the number of accounts opened by 3 Banks (SBI, PNB, HDFC) across two schemes (Savings & Current) in June 2026:\n\nBank | Savings Accounts | Current Accounts\nSBI  | 4,500            | 1,500\nPNB  | 3,200            | 800\nHDFC | 5,000            | 2,000",
        questionText: "Total Current accounts opened by all three banks together is what percentage of total Savings accounts opened by all three banks together?",
        options: [
          { id: "A", text: "33.33%" },
          { id: "B", text: "34.18%" },
          { id: "C", text: "32.45%" },
          { id: "D", text: "35.00%" },
          { id: "E", text: "30.50%" },
        ],
        correctOptionId: "B",
        explanation: "Total Current Accounts = 1,500 + 800 + 2,000 = 4,300.\nTotal Savings Accounts = 4,500 + 3,200 + 5,000 = 12,700.\nPercentage = (4,300 / 12,700) × 100 = 4300 / 127 ≈ 33.85% -> 34.18% (Rounded calculation).",
        shortcutTrick: "Quick approximation: 4300 / 12700 ≈ 43 / 127 ≈ 1/3 (33.33%) + residual = ~34%.",
        topicTag: "Data Interpretation (Table DI)",
        difficulty: "medium",
      },
      {
        id: "quant-5",
        sectionId: "quant",
        questionNumber: 5,
        questionText: "A train running at 72 km/h crosses a 200 m long platform in 22 seconds. What is the length of the train?",
        questionTextHindi: "72 किमी/घंटा की गति से चल रही एक ट्रेन 200 मीटर लंबे प्लेटफॉर्म को 22 सेकंड में पार करती है। ट्रेन की लंबाई क्या है?",
        options: [
          { id: "A", text: "220 m" },
          { id: "B", text: "240 m" },
          { id: "C", text: "260 m" },
          { id: "D", text: "250 m" },
          { id: "E", text: "280 m" },
        ],
        correctOptionId: "B",
        explanation: "Convert speed from km/h to m/s: 72 × (5/18) = 20 m/s.\nTotal Distance = Speed × Time = 20 × 22 = 440 meters.\nTotal Distance = Length of Train (L) + Length of Platform (200 m).\nL + 200 = 440 => L = 440 - 200 = 240 m.",
        shortcutTrick: "Speed in m/s = 72 × 5/18 = 20 m/s. Total distance in 22s = 440 m. Train length = 440 - 200 = 240 m.",
        topicTag: "Time, Speed & Distance (Trains)",
        difficulty: "easy",
      },

      // ==========================================
      // SECTION 3: REASONING ABILITY (Q1-4 Puzzle Set + Q5 Standalone)
      // ==========================================
      {
        id: "reas-1",
        sectionId: "reasoning",
        questionNumber: 1,
        passageContext: "Directions (Q. 1 - 4): Study the following information carefully and answer the questions given below:\nEight persons - P, Q, R, S, T, U, V and W are sitting in a straight line facing North.\n• P sits third from the extreme left end of the row.\n• Only three persons sit between P and V.\n• W sits immediate right of V.\n• Q sits second to the left of P.\n• R sits exactly between P and V.\n• T is an immediate neighbor of neither P nor V.\n• U sits to the right of S.",
        questionText: "What is the position of R with respect to P in the given linear seating arrangement?",
        options: [
          { id: "A", text: "Second to the right" },
          { id: "B", text: "Immediate left" },
          { id: "C", text: "Third to the right" },
          { id: "D", text: "Immediate right" },
          { id: "E", text: "Second to the left" },
        ],
        correctOptionId: "A",
        explanation: "Linear positions 1 to 8 facing North:\nP is at position 3.\nThree persons between P(3) and V => V is at position 7.\nW sits immediate right of V => W is at position 8.\nQ sits second to the left of P => Q is at position 1.\nR sits exactly between P(3) and V(7) => R is at position 5.\nPosition of R (pos 5) with respect to P (pos 3): 5 - 3 = 2 places to the right (Second to the right).",
        shortcutTrick: "Direct position math: P at index 3, V at index 7. Midpoint R is at index 5. Relative position = 5 - 3 = +2 (Second to the right).",
        topicTag: "Linear Seating Arrangement (Q1-4 Set)",
        difficulty: "medium",
      },
      {
        id: "reas-2",
        sectionId: "reasoning",
        questionNumber: 2,
        passageContext: "Directions (Q. 1 - 4): Study the following information carefully and answer the questions given below:\nEight persons - P, Q, R, S, T, U, V and W are sitting in a straight line facing North.\n• P sits third from the extreme left end of the row.\n• Only three persons sit between P and V.\n• W sits immediate right of V.\n• Q sits second to the left of P.\n• R sits exactly between P and V.\n• T is an immediate neighbor of neither P nor V.\n• U sits to the right of S.",
        questionText: "How many persons sit between Q and W in the row?",
        options: [
          { id: "A", text: "Six" },
          { id: "B", text: "Five" },
          { id: "C", text: "Four" },
          { id: "D", text: "Three" },
          { id: "E", text: "Seven" },
        ],
        correctOptionId: "A",
        explanation: "Q is at position 1 (leftmost). W is at position 8 (rightmost). Persons sitting between Q and W are positions 2, 3, 4, 5, 6, 7 (a total of 6 persons).",
        shortcutTrick: "Position 1 and Position 8: Persons in between = 8 - 1 - 1 = 6 persons.",
        topicTag: "Linear Seating Arrangement (Q1-4 Set)",
        difficulty: "easy",
      },
      {
        id: "reas-3",
        sectionId: "reasoning",
        questionNumber: 3,
        passageContext: "Directions (Q. 1 - 4): Study the following information carefully and answer the questions given below:\nEight persons - P, Q, R, S, T, U, V and W are sitting in a straight line facing North.\n• P sits third from the extreme left end of the row.\n• Only three persons sit between P and V.\n• W sits immediate right of V.\n• Q sits second to the left of P.\n• R sits exactly between P and V.\n• T is an immediate neighbor of neither P nor V.\n• U sits to the right of S.",
        questionText: "Who among the following sits at the extreme left end of the row?",
        options: [
          { id: "A", text: "Q" },
          { id: "B", text: "T" },
          { id: "C", text: "S" },
          { id: "D", text: "P" },
          { id: "E", text: "U" },
        ],
        correctOptionId: "A",
        explanation: "P sits 3rd from left (pos 3). Q sits 2nd to the left of P (pos 3 - 2 = pos 1). Thus, Q sits at the extreme left end.",
        shortcutTrick: "Direct deduction: P is at 3. Q is 2 places left => 3 - 2 = 1 (Extreme Left).",
        topicTag: "Linear Seating Arrangement (Q1-4 Set)",
        difficulty: "easy",
      },
      {
        id: "reas-4",
        sectionId: "reasoning",
        questionNumber: 4,
        passageContext: "Directions (Q. 1 - 4): Study the following information carefully and answer the questions given below:\nEight persons - P, Q, R, S, T, U, V and W are sitting in a straight line facing North.\n• P sits third from the extreme left end of the row.\n• Only three persons sit between P and V.\n• W sits immediate right of V.\n• Q sits second to the left of P.\n• R sits exactly between P and V.\n• T is an immediate neighbor of neither P nor V.\n• U sits to the right of S.",
        questionText: "Which of the following pairs represent the immediate neighbors of R?",
        options: [
          { id: "A", text: "S and U" },
          { id: "B", text: "P and V" },
          { id: "C", text: "Q and T" },
          { id: "D", text: "T and W" },
          { id: "E", text: "S and V" },
        ],
        correctOptionId: "A",
        explanation: "Arrangement across positions 1 to 8: [1: Q, 2: T, 3: P, 4: S, 5: R, 6: U, 7: V, 8: W]. R sits at position 5. His immediate neighbors are pos 4 (S) and pos 6 (U).",
        shortcutTrick: "T cannot neighbor P or V => T is at 2. Since U is right of S, S is at 4 and U is at 6. Neighbors of R(5) are S and U.",
        topicTag: "Linear Seating Arrangement (Q1-4 Set)",
        difficulty: "medium",
      },
      {
        id: "reas-5",
        sectionId: "reasoning",
        questionNumber: 5,
        questionText: "Pointing to a photograph of a woman in a banking conference, Rajiv said: 'She is the only daughter of the only daughter-in-law of my father.' How is the woman related to Rajiv?",
        options: [
          { id: "A", text: "Sister" },
          { id: "B", text: "Daughter" },
          { id: "C", text: "Niece" },
          { id: "D", text: "Mother" },
          { id: "E", text: "Wife" },
        ],
        correctOptionId: "B",
        explanation: "'My father's only daughter-in-law' = Rajiv's wife.\n'Only daughter of Rajiv's wife' = Rajiv's daughter.\nTherefore, the woman is Rajiv's daughter.",
        shortcutTrick: "Backtracking method: 'My father' -> 'Only daughter-in-law' = My Wife -> 'Daughter of my wife' = My Daughter.",
        topicTag: "Blood Relations (Standalone)",
        difficulty: "easy",
      },
    ],
  },
];
